#!/usr/bin/env bash
# =============================================================================
# WanderPlan AI — Infrastructure-as-Code Setup Script
# Replaces Terraform — idempotent provisioning for self-hosted deployment
#
# Usage:
#   ./setup.sh                      # Full setup
#   ./setup.sh --verify             # Verify existing installation
#   ./setup.sh --teardown           # Remove everything
#   ./setup.sh --skip-docker        # Run setup but skip Docker/Docker Compose phases
# =============================================================================

set -euo pipefail

SKIP_DOCKER=0
# Allow simple flag parsing for --skip-docker
for _arg in "$@"; do
    case "${_arg}" in
        --skip-docker)
            SKIP_DOCKER=1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INFRA_DIR="${PROJECT_ROOT}/infrastructure"
PROD_DIR="${INFRA_DIR}/production"
ENV_FILE="${PROJECT_ROOT}/.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${BLUE}[setup]${NC} $*"; }
ok()   { echo -e "${GREEN}  ✓${NC} $*"; }
warn() { echo -e "${YELLOW}  ⚠${NC} $*"; }
fail() { echo -e "${RED}  ✗${NC} $*"; }

# ---------------------------------------------------------------------------
# Phase 0: Pre-requisites validation
# ---------------------------------------------------------------------------
check_prerequisites() {
    log "Checking prerequisites..."
    local missing=0

    # Docker (optionally skipped)
    if [ "${SKIP_DOCKER:-0}" -eq 0 ]; then
        if command -v docker &>/dev/null; then
            local dv=$(docker --version | awk '{print $3}' | tr -d ',')
            ok "Docker ${dv}"
        else
            fail "Docker not installed"
            missing=1
        fi

        # Docker Compose
        if docker compose version &>/dev/null; then
            local dcv=$(docker compose version --short)
            ok "Docker Compose ${dcv}"
        else
            fail "Docker Compose not installed"
            missing=1
        fi
    else
        warn "Skipping Docker/Docker Compose checks (SKIP_DOCKER=1)"
    fi

    # Minimum resources check
    local total_mem_kb=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}' || echo "0")
    local total_mem_gb=$((total_mem_kb / 1024 / 1024))
    if [ "${total_mem_gb}" -ge 16 ]; then
        ok "RAM: ${total_mem_gb}GB (recommended: 16GB+)"
    elif [ "${total_mem_gb}" -ge 8 ]; then
        warn "RAM: ${total_mem_gb}GB (minimum for production, 16GB+ recommended)"
    else
        warn "RAM: ${total_mem_gb}GB (insufficient — 16GB+ recommended)"
    fi

    local cpu_count=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo "0")
    if [ "${cpu_count}" -ge 8 ]; then
        ok "CPUs: ${cpu_count} cores"
    elif [ "${cpu_count}" -ge 4 ]; then
        warn "CPUs: ${cpu_count} cores (minimum, 8+ recommended)"
    else
        warn "CPUs: ${cpu_count} cores (insufficient — 8+ recommended)"
    fi

    # Disk space (need at least 50GB free)
    local free_gb=$(df -BG / | tail -1 | awk '{print $4}' | tr -d 'G')
    if [ "${free_gb}" -ge 50 ]; then
        ok "Disk: ${free_gb}GB free"
    else
        warn "Disk: ${free_gb}GB free (50GB+ recommended)"
    fi

    # Required system settings for OpenSearch/Kafka
    local vm_max=$(sysctl -n vm.max_map_count 2>/dev/null || echo "0")
    if [ "${vm_max}" -ge 262144 ]; then
        ok "vm.max_map_count=${vm_max}"
    else
        warn "vm.max_map_count=${vm_max} (needs 262144 for OpenSearch)"
        echo "  Fix: sudo sysctl -w vm.max_map_count=262144"
        echo "  Persist: echo 'vm.max_map_count=262144' | sudo tee -a /etc/sysctl.conf"
    fi

    if [ "${missing}" -ne 0 ]; then
        fail "Missing prerequisites. Install them first."
        exit 1
    fi

    ok "All prerequisites met"
}

# ---------------------------------------------------------------------------
# Phase 1: Generate environment file
# ---------------------------------------------------------------------------
generate_env() {
    log "Generating environment file..."

    if [ -f "${ENV_FILE}" ]; then
        warn ".env already exists. Skipping generation."
        warn "To regenerate: rm ${ENV_FILE} && re-run setup"
        return
    fi

    # Generate secure random passwords
    gen_password() { openssl rand -base64 24 | tr -d '=/+' | head -c 32; }

    cat > "${ENV_FILE}" << EOF
# =============================================================================
# WanderPlan AI — Production Environment Variables
# Generated by setup.sh on $(date -Iseconds)
# =============================================================================

# --- Domain ---
DOMAIN=localhost

# --- Database Passwords (auto-generated) ---
POSTGRES_PASSWORD=$(gen_password)
PG_REPL_PASSWORD=$(gen_password)
MONGO_PASSWORD=$(gen_password)
REDIS_PASSWORD=$(gen_password)

# --- Object Storage ---
MINIO_ACCESS_KEY=wanderplan
MINIO_SECRET_KEY=$(gen_password)

# --- Monitoring ---
GRAFANA_PASSWORD=$(gen_password)
TRAEFIK_DASHBOARD_AUTH=admin:$(openssl passwd -apr1 "$(gen_password)" 2>/dev/null || echo 'changeme')

# --- LLM API Keys (FILL THESE IN) ---
ANTHROPIC_API_KEY=
LLM_MODEL=claude-sonnet-4-20250514
LLM_FALLBACK_MODEL=llama3.1:8b

# --- External APIs (FILL THESE IN) ---
PINECONE_API_KEY=
GOOGLE_PLACES_API_KEY=
AMADEUS_API_KEY=
AMADEUS_API_SECRET=
YELP_API_KEY=
WEATHER_API_KEY=

# --- Alerting ---
SLACK_WEBHOOK_URL=
PAGERDUTY_SERVICE_KEY=
ALERT_EMAIL_FROM=alerts@wanderplan.local
ALERT_EMAIL_TO=ops@wanderplan.local
SMTP_HOST=smtp.gmail.com:587
SMTP_USER=
SMTP_PASS=

# --- TLS ---
ACME_EMAIL=admin@wanderplan.local

# --- Backup ---
BACKUP_ROOT=/opt/wanderplan/backups
BACKUP_ENCRYPTION_KEY=$(gen_password)
REMOTE_BACKUP=

# --- Log Level ---
LOG_LEVEL=INFO
EOF

    chmod 600 "${ENV_FILE}"
    ok "Environment file created at ${ENV_FILE}"
    warn "IMPORTANT: Edit ${ENV_FILE} and fill in API keys before starting"
}

# ---------------------------------------------------------------------------
# Phase 2: Create directory structure
# ---------------------------------------------------------------------------
create_directories() {
    log "Creating directory structure..."

    # On Windows (Git Bash/MSYS) avoid creating Linux system paths
    local uname_s=$(uname -s 2>/dev/null || echo '')
    if echo "${uname_s}" | grep -Eiq "mingw|msys|cygwin"; then
        warn "Detected Windows/MSYS environment; skipping creation of Linux system directories"
        return
    fi

    local dirs=(
        /opt/wanderplan/backups
        /opt/wanderplan/data/postgres
        /opt/wanderplan/data/mongodb
        /opt/wanderplan/data/redis
        /opt/wanderplan/data/opensearch
        /opt/wanderplan/data/kafka
        /opt/wanderplan/data/minio
        /opt/wanderplan/logs
        /var/log/wanderplan
    )

    for dir in "${dirs[@]}"; do
        mkdir -p "${dir}" 2>/dev/null || sudo mkdir -p "${dir}"
        ok "Created ${dir}"
    done
}

# ---------------------------------------------------------------------------
# Phase 3: Set system parameters
# ---------------------------------------------------------------------------
configure_system() {
    log "Configuring system parameters..."

    # Detect Windows/MSYS and skip system-level configuration there
    local uname_s=$(uname -s 2>/dev/null || echo '')
    if echo "${uname_s}" | grep -Eiq "mingw|msys|cygwin"; then
        warn "Detected Windows/MSYS environment; skipping system parameter configuration"
        return
    fi

    # OpenSearch requires this
    local vm_max=$(sysctl -n vm.max_map_count 2>/dev/null || echo "0")
    if [ "${vm_max:-0}" -lt 262144 ]; then
        sudo sysctl -w vm.max_map_count=262144
        echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf > /dev/null
        ok "Set vm.max_map_count=262144"
    fi

    # Increase file descriptor limits
    if ! grep -q "wanderplan" /etc/security/limits.conf 2>/dev/null; then
        echo "# WanderPlan AI" | sudo tee -a /etc/security/limits.conf > /dev/null
        echo "* soft nofile 65536" | sudo tee -a /etc/security/limits.conf > /dev/null
        echo "* hard nofile 65536" | sudo tee -a /etc/security/limits.conf > /dev/null
        ok "Increased file descriptor limits"
    fi
}

# ---------------------------------------------------------------------------
# Phase 4: Generate MongoDB keyfile for replica set auth
# ---------------------------------------------------------------------------
generate_mongo_keyfile() {
    log "Generating MongoDB replica set keyfile..."
    local keyfile="${INFRA_DIR}/scripts/mongo-keyfile"

    if [ -f "${keyfile}" ]; then
        ok "Keyfile already exists"
        return
    fi

    openssl rand -base64 756 > "${keyfile}"
    chmod 400 "${keyfile}"
    ok "MongoDB keyfile generated"
}

# ---------------------------------------------------------------------------
# Phase 5: Create Kafka topics
# ---------------------------------------------------------------------------
create_kafka_topics() {
    log "Creating Kafka topics..."

    local topics=(
        "wanderplan.agent.requests:12:3"
        "wanderplan.agent.responses:12:3"
        "wanderplan.trip.context:12:3"
        "wanderplan.user.prompts:6:3"
        "wanderplan.user.replies:6:3"
        "wanderplan.agent.registry:3:3"
        "wanderplan.dlq:3:3"
    )

    for topic_cfg in "${topics[@]}"; do
        IFS=':' read -r topic partitions replication <<< "${topic_cfg}"
        docker exec wanderplan-kafka-1 kafka-topics \
            --bootstrap-server localhost:9092 \
            --create \
            --topic "${topic}" \
            --partitions "${partitions}" \
            --replication-factor "${replication}" \
            --if-not-exists \
            2>/dev/null && ok "Topic: ${topic}" || warn "Topic ${topic} may already exist"
    done
}

# ---------------------------------------------------------------------------
# Phase 6: Initialize MinIO buckets
# ---------------------------------------------------------------------------
init_minio_buckets() {
    log "Initializing MinIO buckets..."

    # Source env vars
    source "${ENV_FILE}" 2>/dev/null || true

    local buckets=(
        "wanderplan-static"
        "wanderplan-photos"
        "wanderplan-media"
        "wanderplan-exports"
        "wanderplan-backups"
    )

    docker run --rm --network wanderplan-private \
        minio/mc:latest bash -c "
            mc alias set wanderplan http://minio:9000 \
                ${MINIO_ACCESS_KEY:-wanderplan} ${MINIO_SECRET_KEY:-wanderplan-secret-key}
            $(for b in "${buckets[@]}"; do echo "mc mb --ignore-existing wanderplan/${b}"; done)
            # Set lifecycle: delete exports after 30 days
            mc ilm rule add --expire-days 30 wanderplan/wanderplan-exports
            # Public read for static assets
            mc anonymous set download wanderplan/wanderplan-static
        " 2>/dev/null && ok "MinIO buckets created" || warn "MinIO bucket setup needs retry after services start"
}

# ---------------------------------------------------------------------------
# Phase 7: Initialize MongoDB replica set
# ---------------------------------------------------------------------------
init_mongo_replicaset() {
    log "Initializing MongoDB replica set..."

    docker exec wanderplan-mongo-primary mongosh --eval '
        rs.initiate({
            _id: "rs0",
            members: [
                { _id: 0, host: "mongo-primary:27017", priority: 2 },
                { _id: 1, host: "mongo-secondary:27017", priority: 1 }
            ]
        })
    ' 2>/dev/null && ok "MongoDB replica set initialized" || warn "Replica set may already be initialized"
}

# ---------------------------------------------------------------------------
# Phase 8: Set up cron jobs
# ---------------------------------------------------------------------------
setup_cron() {
    log "Setting up backup cron jobs..."

    # Skip cron setup on Windows/MSYS
    local uname_s=$(uname -s 2>/dev/null || echo '')
    if echo "${uname_s}" | grep -Eiq "mingw|msys|cygwin"; then
        warn "Detected Windows/MSYS environment; skipping cron setup"
        return
    fi

    local cron_line="*/30 * * * * ${INFRA_DIR}/backup/backup.sh >> /var/log/wanderplan/backup.log 2>&1"

    if crontab -l 2>/dev/null | grep -q "wanderplan"; then
        ok "Cron jobs already configured"
    else
        (crontab -l 2>/dev/null || true; echo "${cron_line}") | crontab -
        ok "Backup cron installed (every 30 minutes)"
    fi
}

# ---------------------------------------------------------------------------
# Phase 9: Pull images and start services
# ---------------------------------------------------------------------------
start_services() {
    log "Pulling images and starting services..."

    cd "${PROD_DIR}"
    source "${ENV_FILE}" 2>/dev/null || true

    # Build agent image
    docker compose -f docker-compose.prod.yml build --parallel 2>&1
    ok "Agent images built"

    # Start infrastructure first
    docker compose -f docker-compose.prod.yml up -d \
        redis-master redis-replica-1 redis-replica-2 \
        redis-sentinel-1 redis-sentinel-2 redis-sentinel-3 \
        postgres-primary kafka-controller kafka-1 kafka-2 kafka-3 \
        mongo-primary opensearch-node1 minio \
        jaeger prometheus alertmanager grafana
    ok "Infrastructure services started"

    log "Waiting for infrastructure to be ready..."
    sleep 30

    # Start remaining infra
    docker compose -f docker-compose.prod.yml up -d \
        postgres-replica mongo-secondary opensearch-node2 \
        opensearch-dashboards kafka-ui \
        traefik cdn-cache ollama \
        node-exporter cadvisor
    ok "Supporting services started"

    sleep 15

    # Start agents
    docker compose -f docker-compose.prod.yml up -d \
        orchestrator bucket-list timing interest-profiler \
        health-accessibility poi-discovery duration-optimizer \
        availability budget flight accommodation dining \
        itinerary calendar group-coordinator
    ok "All 15 agents started"

    # Start autoscaler
    docker compose -f docker-compose.prod.yml up -d autoscaler
    ok "Autoscaler started"
}

# ---------------------------------------------------------------------------
# Phase 10: Health verification
# ---------------------------------------------------------------------------
verify_health() {
    log "Verifying system health..."
    sleep 30

    local total=0
    local healthy=0

    # Check each agent
    for port in $(seq 8000 8014); do
        total=$((total + 1))
        if curl -sf "http://localhost:${port}/health" > /dev/null 2>&1; then
            healthy=$((healthy + 1))
            ok "Port ${port}: healthy"
        else
            fail "Port ${port}: unreachable"
        fi
    done

    echo ""
    log "==========================================="
    if [ "${healthy}" -ge 15 ]; then
        ok "ALL ${healthy}/${total} agents healthy"
    elif [ "${healthy}" -ge 10 ]; then
        warn "${healthy}/${total} agents healthy (some still starting)"
    else
        fail "${healthy}/${total} agents healthy (check logs)"
    fi
    log "==========================================="

    log "Access points:"
    echo "  API:          https://api.\${DOMAIN}"
    echo "  Grafana:      https://grafana.\${DOMAIN}"
    echo "  Jaeger:       https://tracing.\${DOMAIN}"
    echo "  Kafka UI:     https://kafka.\${DOMAIN}"
    echo "  MinIO:        https://storage.\${DOMAIN}"
    echo "  Prometheus:   https://prometheus.\${DOMAIN}"
    echo "  OpenSearch:   https://search.\${DOMAIN}"
}

# ---------------------------------------------------------------------------
# Teardown
# ---------------------------------------------------------------------------
teardown() {
    log "Tearing down all services..."
    cd "${PROD_DIR}"
    docker compose -f docker-compose.prod.yml down -v --remove-orphans
    ok "All services stopped and volumes removed"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    echo "==========================================="
    echo "  WanderPlan AI — Infrastructure Setup"
    echo "  $(date)"
    echo "==========================================="

    case "${1:-}" in
        --verify)
            check_prerequisites
            if [ "${SKIP_DOCKER:-0}" -eq 0 ]; then
                verify_health
            else
                warn "Skipping health verification because Docker was skipped"
            fi
            ;;
        --teardown)
            teardown
            ;;
        *)
            check_prerequisites
            generate_env
            create_directories
            configure_system
            generate_mongo_keyfile
            if [ "${SKIP_DOCKER:-0}" -eq 0 ]; then
                start_services
                create_kafka_topics
                init_minio_buckets
                init_mongo_replicaset
                setup_cron
                verify_health
            else
                warn "Skipping Docker/Compose service startup and related steps (SKIP_DOCKER=1)"
                setup_cron
            fi
            ;;
    esac
}

main "$@"
